{% set event_types = ["UG - TRAVEL - COLLEGE FAIR TEMPLATE","UG - TRAVEL - HIGH SCHOOL VISIT TEMPLATE","SUMMER/FALL/SPRING OVERVIEW VISITS!","UG - TRAVEL - HIGH SCHOOL VIRTUAL VISIT TEMPLATE","PRIVATE VISIT","THEATRE AUDITIONS","WAGNER EXPERIENCE DAY","PHYSICIAN ASSISTANT INTERVIEW DAY","TALK TO A SEAHAWK","LIVE VIRTUAL CAMPUS TOUR","OVERVIEW VISITS","VIRTUAL OVERVIEW VISIT","TRANSFER STUDENT VISIT DAYS","JOIN THE BAND DAY","SUMMER OVERVIEW VISIT DAY","ADMITTED STUDENTS DAY","SING AT WAGNER DAYS","LIVE VIRTUAL CAMPUS TOURS- SATURDAYS","THEATRE DESIGN TECHNOLOGY MANAGEMENT INTERVIEW DAY","UG - TRAVEL - SPECIAL EVENT TEMPLATE","LIVE THEMED WAGNER EXPERIENCE DAYS (VIRTUAL)","SECRET LIFE OF A SEAHAWK"] %}

WITH lc_dates AS (
    SELECT 
        Ref
        , Period
        , [App Submitted] AS APP_DATE
        , [Admit Date] AS ADM_DATE
        , [Deposit Date] AS DEP_DATE
    FROM apps
)
SELECT 
    events.Ref
    , lc_dates.Period
    {% for event_type in event_types %}
    , CASE WHEN SUM(CASE WHEN UPPER(EVENT_CATEGORY) = '{{event_type}}' AND (EVENT_DATE < APP_DATE OR APP_DATE IS NULL) THEN 1.0 ELSE 0.0 END)>0 THEN 'YES' ELSE 'NO' END as FG_EVT_X_INQ
    , CASE WHEN SUM(CASE WHEN UPPER(EVENT_CATEGORY) = '{{event_type}}' AND (EVENT_DATE < ADM_DATE OR ADM_DATE IS NULL) THEN 1.0 ELSE 0.0 END)>0 THEN 'YES' ELSE 'NO' END as FG_EVT_X_APP
    , CASE WHEN SUM(CASE WHEN UPPER(EVENT_CATEGORY) = '{{event_type}}' AND (EVENT_DATE < DEP_DATE OR DEP_DATE IS NULL) THEN 1.0 ELSE 0.0 END)>0 THEN 'YES' ELSE 'NO' END as FG_EVT_X_ADM
    , CASE WHEN SUM(CASE WHEN UPPER(EVENT_CATEGORY) = '{{event_type}}' THEN 1.0 ELSE 0.0 END)>0 THEN 'YES' ELSE 'NO' END as FG_EVT_X_DEP
    {% endfor %}
FROM events 
LEFT JOIN lc_dates
ON events.Ref = lc_dates.Ref 
GROUP BY events.Ref, lc_dates.Period