
version: 2

models:
  - name: file_overview
    description: "Gets the # of rows per file"
    columns:
      - name: File Name
        description: "The primary key for this table"
        tests:
          - unique
          - not_null